import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'domain_strings.dart';

extension AlgorithmStringsExt on AppLocalizations {
  ValidationStrings get validationStrings => ValidationStrings(
    day: 'يوم',
    hour: 'ساعة',
    minute: 'دقيقة',
    second: 'ثانية',
    morning: 'صباحاً',
    afternoon: 'مساءً',
    evening: 'مساءً',
    night: 'ليلاً',
    today: 'اليوم',
    tomorrow: 'غداً',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    thisYear: 'هذا العام',
    lastWeek: 'الأسبوع الماضي',
    lastMonth: 'الشهر الماضي',
    lastYear: 'العام الماضي',
    nextWeek: 'الأسبوع القادم',
    nextMonth: 'الشهر القادم',
    nextYear: 'العام القادم',
    daily: 'يومياً',
    weekly: 'أسبوعياً',
    monthly: 'شهرياً',
    yearly: 'سنوياً',
    generateSchedule: 'توليد الجدول',
    validateSchedule: 'التحقق من الجدول',
    clearSchedule: 'مسح الجدول',
    exportPdf: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    printSchedule: 'طباعة الجدول',
    addTeacher: 'إضافة معلم',
    editTeacher: 'تعديل معلم',
    deleteTeacher: 'حذف معلم',
    teacherDetails: 'تفاصيل المعلم',
    fullName: 'الاسم الكامل',
    specialization: 'التخصص',
    maxWeeklyHours: 'أقصى ساعات أسبوعية',
    maxDailyHours: 'أقصى ساعات يومية',
    noTeachersFound: 'لم يتم العثور على معلمين',
    addClassroom: 'إضافة فصل',
    editClassroom: 'تعديل فصل',
    deleteClassroom: 'حذف فصل',
    classroomName: 'اسم الفصل',
  );

  GeneratorStrings get generatorStrings => GeneratorStrings(
    initializing: 'جاري التهيئة...',
    loadingData: 'جاري تحميل البيانات...',
    preprocessing: 'جاري المعالجة المسبقة...',
    generating: 'جاري إنشاء الجدول...',
    optimizing: 'جاري تحسين الجدول...',
    validating: 'جاري التحقق من الجدول...',
    finishing: 'اللمسات الأخيرة...',
    completed: 'تم بنجاح',
    classrooms: 'الفصول',
    subjects: 'المواد',
    grades: 'الصفوف',
    saving: 'جاري الحفظ...',
    failed: 'فشل التوليد',
    cancelled: 'تم الإلغاء',
    timeout: 'انتهى الوقت',
    noData: 'بيانات غير مكتملة',
    error: 'حدث خطأ',
  );
}
